import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{

          }}
        >
          <p>WeDoAllTech</p>
        </header>
        {children}
        <footer
          style={{

          }}
        >
        </footer>
      </body>
    </html>
  );
}
